export const ACTION = {
  SET_PRODUCT: "SET_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ADD_CART: "ADD_CART",
  DELETE_CART: "DELETE_CART",
  INCREAMENT_QUANTITY: "INCREAMENT_QUANTITY",
  DECREAMENT_QUANTITY: "DECREAMENT_QUANTITY",
};
